[build]
  command = "npm run build"
  publish = "out"

[build.environment]
NEXT_PUBLIC_SUPABASE_URL=https://mkqnfufapcmycvncaqhj.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rcW5mdWZhcGNteWN2bmNhcWhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ4MjE4MTIsImV4cCI6MjA4MDM5NzgxMn0.gJjDPDZLyAxA-TwjxvevGwYYFt9AMu1K5eY-rinKhno
  NEXT_PUBLIC_DEV_SUPABASE_REDIRECT_URL = "https://tombola-bem-tech-2025.netlify.app/auth/callback"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
